### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Marwerk** [Runewerk/flashcenter#2]
Install Authentication middleware with Nando

**Comment by Marwerk** [comment]
@Gords aca

**Comment by Marwerk** [comment]
@Gords en el branch https://github.com/Runewerk/flashcenter/tree/passport-without-google

hice git checkout passport-without-google, git pull

corri el server
click en boton registro, completar el form y al hacer submit recibi:

```
app-1  | Error: secret option required for sessions
app-1  |     at session (/app/node_modules/express-session/index.js:204:12)
app-1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
app-1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
app-1  |     at /app/node_modules/express/lib/router/index.js:286:9
app-1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
app-1  |     at next (/app/node_modules/express/lib/router/index.js:280:10)
app-1  |     at serveStatic (/app/node_modules/serve-static/index.js:75:16)
app-1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
app-1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
app-1  |     at /app/node_modules/express/lib/router/index.js:286:9

```

al hacer submit en el login form, el mismo error:

```
app-1  | Error: secret option required for sessions
app-1  |     at session (/app/node_modules/express-session/index.js:204:12)
app-1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
app-1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
app-1  |     at /app/node_modules/express/lib/router/index.js:286:9
app-1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
app-1  |     at next (/app/node_modules/express/lib/router/index.js:280:10)
app-1  |     at serveStatic (/app/node_modules/serve-static/index.js:75:16)
app-1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
app-1  |     at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
app-1  |     at /app/node_modules/express/lib/router/index.js:286:9
```


y la imagen es el browser dev console error al hacer submit los forms:

![Image](https://github.com/Runewerk/flashcenter/assets/137423785/1c4b6ce9-3758-4638-b1ea-4b704723d139)
